### ISSUE TITLE
Improper float formatting

### ISSUE THREAD

**Issue by efritz** [dave/jennifer#39] opened 2018-07-12 21:28 UTC
This not is no longer true - maybe it was in a past version of Go? Seems that this should either be removed or the **int** version should be formatted in place of the %#v.0 so that we don't get .0.0 at the end for newer versions. This results in invalid generated code.

https://github.com/dave/jennifer/blob/5ba2c0232d2f848cf1e390db03b100f0838f6d55/jen/tokens.go#L52

**Comment by dave** [comment] 2018-07-13 02:30
Which version of Go are you using?

**Comment by dave** [comment] 2018-07-13 02:49
I don't seem to be able to reproduce this in the latest Go v1.10.3... This test still passes:

```go
func TestFmtPackage(t *testing.T) {
	if fmt.Sprintf("%#v", float64(0.0)) != "0" {
		t.Fatal("fmt package no longer shows float bug")
	}
}
```

Perhaps you can show me an example that's failing for you? I can add a more defensive condition on that if... something like:

```go
if v == float64(int64(v)) && fmt.Sprintf("%#v", 1.0) == "1" {
```

... that might work... but I'd like to understand the problem better first and be able to reproduce it myself...

**Comment by dave** [comment] 2018-07-13 03:59
I believe the bug in the standard library comes from these lines: [here](https://github.com/golang/go/blob/master/src/fmt/print.go#L997-L998) and [here](https://github.com/golang/go/blob/master/src/fmt/format.go#L485). The block in `format.go` is concerned with adding the decimal point and additional decimals when we're in the `sharp` mode (e.g. using the `#` modifier). However, it looks like it didn't take into account the fact that when the `v` verb is used, the `sharp` flag is set to `false` and `sharpV` is set to true (in `print.go`). 

It looks like [this commit](https://github.com/golang/go/commit/e97f407ec164174187d6fbb2f7332d6fb3176e9e) changed this behaviour in the last year... but I believe it still works like this in master. From the looks of the description in the commit, `%#v` was intended to be included in the change, but there's no test case for that... Perhaps @martisch would like to comment on what is expected from `fmt.Printf("%#v", float64(0.0))`?

**Comment by dave** [comment] 2018-07-13 04:02
I'll add a Go issue and see what the consensus is.

**Comment by dave** [comment] 2018-07-13 04:35
I've added a more defensive check here and released it as v1.0.1: https://github.com/dave/jennifer/commit/1e7350a4056feee9ba0b013d83fe91957929dad1

**Comment by efritz** [comment] 2018-07-13 12:48
Thanks for the quick response! Here's a sample program that displays this issue as it's still present in the most recent commit.

This occurs with both go 9 and 10.

```
package main

import (
	"bytes"
	"fmt"

	"github.com/dave/jennifer/jen"
)

func main() {
	file := jen.NewFile("example")

	file.Var().Id("x").Op("=").Lit(1e+06)

	buffer := &bytes.Buffer{}
	if err := file.Render(buffer); err != nil {
		panic(err.Error())
	}

	fmt.Println(buffer.String())
}

```

Specifically, this generates the following output, which can't be formatted by go/format.

```
package example

var x = 1e+06.0
```

**Comment by dave** [comment] 2018-07-14 06:03
Oh wow, thanks for finding this. I had no idea 1e6 would be a float64. Interesting. But also `fmt.Printf("%#v\n", 1000000.0)` prints `1e+06`, so we have to be more careful. I'll do a proper fix that's even more defensive.

**Comment by dave** [comment] 2018-07-14 06:19
OK I think this is better... It takes the formatted value and adds `.0` only if it doesn't contain `.` or `e`. I've pushed the change and tagged it v1.0.2... Give that a go.

**Comment by dave** [comment] 2018-07-16 13:46
I'm pretty sure this is fixed now, so I'm going to close it for now. If there'a any more problems, feel free to re-open. Thanks for reporting it!

**Closed by dave** 2018-07-16 13:46 UTC

**Comment by dave** [comment] 2018-07-16 13:48
BTW it looks like my suggestion to fix this behaviour in the standard library `fmt` package was accepted: https://github.com/golang/go/issues/26363 (won't be fixed until go1.12 though)

**Comment by dave** [comment] 2018-09-12 04:44
Could do this but I’d prefer the code to be as clean as possible...

**Comment by kortschak** [comment] 2018-09-12 04:57
It's generated. The issue is that the change that has gone in to fmt to fix this has broken tests for Gonum mat in a way that is difficult to fix and impossible to fix nicely.

**Comment by dave** [comment] 2018-09-12 05:39
Probably best to point this out over in the issue in the golang repo. I wouldn’t expect a change like this to be entirely consequence free.

**Comment by dave** [comment] 2018-09-12 05:43
FYI this project already has a work-around that works with both go `1.11` and `master`: https://github.com/dave/jennifer/commit/94ad458fe2628ada73d7c7ed0ca2ceae79a4fbea

**Comment by kortschak** [comment] 2018-09-12 05:56
I have just done that. Thanks.
